DRAFT: Feature/30 catch all
hitobito-bbt/hitobito pull request #3
Opened 2021-04-09 13:41 UTC by luca-bruegger

2021-04-12 05:54 UTC, psunix commented on app/controllers/mailing_lists/imap_mails_controller.rb
> +      params[:mail_ids].split(',').map { |id| id.to_i }
```suggestion
      params[:mail_ids]&.split(',')&.map(&:to_i) || []
```
one-liner for param_ids

2021-04-12 05:55 UTC, psunix commented on app/controllers/mailing_lists/imap_mails_controller.rb
> +    @counts ||= imap.counts
cache counts inside imap connector ?

2021-04-12 05:56 UTC, psunix commented on app/decorators/mailing_list_mails_decorator.rb
> +# encoding: utf-8
if this file is required ... add right header.
maybe remove file ?

2021-04-12 05:56 UTC, psunix commented on app/helpers/filter_navigation/mailing_list/mails.rb
> +# encoding: utf-8
header ...

2021-04-12 05:59 UTC, psunix commented on app/helpers/filter_navigation/mailing_list/mails.rb
> +        @counts ||= template.instance_variable_get('@counts') || {}
no need for caching ...

2021-04-12 06:02 UTC, psunix commented on app/helpers/mailing_lists/mails_helper.rb
> +module MailingLists::MailsHelper
```suggestion
module MailingLists::ImapMailsHelper
```

2021-04-12 06:18 UTC, psunix commented on app/utils/imap/connector.rb
> +  def fetch_by_uid(uid, mailbox = 'inbox')
```suggestion
  def fetch_by_uid(uid, mailbox = :inbox)
```

2021-04-12 06:40 UTC, psunix commented on app/utils/imap/mail.rb
> +
delegate :sender, to: :envelope

2021-04-12 06:43 UTC, psunix commented on app/helpers/mailing_lists/mails_helper.rb
> +  def mail_mailbox_failed?
```suggestion
  def mail_mailbox?(name)
```
when calling in view: mail_mailbox?(:failed)

2021-04-12 06:45 UTC, psunix commented on app/utils/imap/connector.rb
> +  def connect
return if @connected

2021-04-12 06:46 UTC, psunix commented on app/utils/imap/connector.rb
> +  def disconnect
return unless @connected

2021-04-12 06:46 UTC, psunix commented on app/utils/imap/connector.rb
> +    disconnect unless already_connected
remove unless

2021-04-12 06:53 UTC, psunix commented on config/routes.rb
> +    scope module: :mailing_lists do
```suggestion
    scope '/mailing_lists', module: :mailing_lists do
```
then remove mailing_lists from get, delete ...

2021-04-12 07:04 UTC, psunix approved these changes
go go go ... looking pretty good.
some tuning required ...

2021-04-12 07:04 UTC, psunix commented on spec/utils/imap/connector_spec.rb
> +      expect(net_imap).to receive(:disconnect).exactly(3).times
wouldn't it be more efficient to have just one disconnect ?
there's no connect call ?

2021-04-12 07:04 UTC, psunix commented on spec/utils/imap/connector_spec.rb
> +      expect(net_imap).to receive(:status).exactly(3).times.and_return({ 'MESSAGES' => 1 })
3 times? one time for every mailbox? 
maybe it's better to specify the mailbox name?

2021-04-12 07:04 UTC, psunix commented on spec/utils/imap/connector_spec.rb
> +      expect(net_imap).to receive(:disconnect).exactly(3).times
maybe merge this with the follow up case ?

2021-04-12 07:04 UTC, psunix commented on spec/utils/imap/connector_spec.rb
> +      imap_connector.send(:create_if_missing, 'Failed', error)
I would prefer calling for example fetch_mails(:failed) here. 
so no send required and you would not have to call connect first

2021-04-20 15:18 UTC, miosidler commented
WIP imap_mails_controller, imap_mails_controller

2021-04-21 12:31 UTC, psunix commented
- schaut euch Ruby symbols an falls ihr das noch nicht kennt
- achtet immer darauf das niemand irgendwelche unverwünschten Werte via HTTP params einschleusen kann
- siehe auch SQL injection, Rails permitted_params zum vorherigen Punkt
-

2021-04-21 14:10 UTC, psunix commented
- schaut euch Ruby symbols an falls ihr das noch nicht kennt
- achtet immer darauf das niemand irgendwelche unverwünschten Werte via HTTP params einschleusen kann
- siehe auch SQL injection, Rails permitted_params zum vorherigen Punkt

ich habe jetzt mal mailing_lists/imap_mails#index soweit fertig implementiert. 

bitte testet die Implementation auch noch im UI. Dann Delete und Move controller specs fertig stellen.

2021-04-28 14:29 UTC, psunix requested changes
es sieht schon sehr gut aus :partying_face: 
ein paar Dinge müsst ihr noch anschauen:

- Flash message wird nicht angezeigt wenn z.B. server nicht erreichbar
  - Prüft doch welche Exception in welchem Fall zurück gegeben werden
  - z.B. wenn keine Verbindung hergestellt werden kann: Errno::EADDRNOTAVAIL, Cannot assign requested address - connect(2)
  - ein anderer fall wäre wenn der DNS name nicht aufgelöst werden kann
  - wenn das Login fehl schlägt. 
- Das Problem mit den fehlenden Filter-Pills ist auf dem Master branch. Einfach einen anderen Benutzer wie z.B. simon@puzzle.ch benutzen. hito42bito als pw
- Das Port Setting wird heute auch schon von der best. POP3 implementation verwendet!
  - entweder einfach mal default 993 setzen, oder imap_port setting hinzufügen
- Noch zwei Kommentare weiter unten

2021-04-28 14:29 UTC, psunix commented on spec/controllers/mailing_lists/imap_mails_move_controller_spec.rb
> +      sign_in(people(:bottom_member))
make sure imap_connector is never called !

2021-04-28 14:53 UTC, psunix commented
![image](https://user-images.githubusercontent.com/655627/116424849-25c66900-a842-11eb-9004-e170cad1b044.png)

buttons sind teils english, teils deutsch.

bitte noch übersetzen.

2021-04-28 14:58 UTC, psunix commented
wenn ich ein mail von der Inbox z.b. in den SPAM folder verschiebe, dann wird das mail kopiert und nicht verschoben. 
muss man ggf. noch ein delete anfügen?

2021-04-30 11:28 UTC, closed without merging